version: '2'
services:
  node-red:
    restart: unless-stopped
    build: node-red
    user: "root"
    volumes:
      - "${TTN_DASHBOARD_DATA}/var/lib/node-red:/data"
    ports:
      - "1880:1880"
    links:
      - influxdb
    
  influxdb:
    restart: unless-stopped
    image: tutum/influxdb
    env_file: influxdb/.env
    volumes:
      - "${TTN_DASHBOARD_DATA}/var/lib/influxdb:/data"
    ports:
      - "8083:8083"
      - "8086:8086"
  
  grafana:
    restart: unless-stopped
    image: grafana/grafana
    env_file: grafana/.env
    volumes:
      - "${TTN_DASHBOARD_DATA}/var/lib/grafana:/var/lib/grafana"
    ports:
      - "80:3000"
    links:
      - influxdb

