version: '2'
services:
  node-red:
    build: node-red
    user: "root"
    volumes:
      - ./node-red/data:/data
    ports:
      - "1880:1880"
    links:
      - influxdb
    
  influxdb:
    image: tutum/influxdb
    env_file: influxdb/.env
    volumes:
      - /var/lib/influxdb:/data
    ports:
      - "8083:8083"
      - "8086:8086"
  
  grafana:
    image: grafana/grafana
    env_file: grafana/.env
    volumes:
      - /var/lib/grafana:/var/lib/grafana 
    ports:
      - "80:3000"
    links:
      - influxdb

